version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: stockly
      POSTGRES_PASSWORD: will
      POSTGRES_DB: stockly
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
